const CONSTANTS = {
    RGP:/^(\b\w+\b\s+){3,}\b\w+\b/,
    BILIBILI_PATTERN: /^https:\/\/www\.bilibili\.com\/video\/BV\w+/,
    YOUTUBE_PATTERN: /^https:\/\/(?:www\.youtube\.com\/(?:watch\?v=|shorts\/)|youtube\.com\/(?:watch\?v=|shorts\/)|youtu\.be\/)[\w-]+/,
    DOI_PATTERN: /^(?:(?:https?:\/\/)?(?:dx\.)?(?:doi\.org|link\.springer\.com\/article)\/)?10\.\d{4,9}\/[-._;()/:A-Z0-9]+$/i,
    XIAOHONGSHU_PATTERN: /^(https:\/\/www\.xiaohongshu\.com\/(explore|discovery|discovery\/item)\/\w+|http:\/\/xhslink\.com\/a\/\w+)/,
    TENCENT_VIDEO_PATTERN: /^https:\/\/v\.qq\.com\/x\/cover\/\w+\/\w+\.html(?:\?.*)?$/,

    SHORT_QUERY_PATTERN: /^(\b\w+\b\s*){1,3}$/,
    CHINESE_TITLE_PATTERN: /^[\u4e00-\u9fa5]{8,}$/,
    PREFIX_PATTERN: /^(-?\w+)(?:-(.*))?/,
    SEARCH_ENGINES: {
        //搜索引擎
        'bd': 'https://www.baidu.com/s?wd=',
        'gg': 'https://www.google.com/search?q=',
        'bi': 'https://www.bing.com/search?q=',
        'sg': 'https://www.so.com/s?q=',
        //视频类
        'bv': 'https://search.bilibili.com/all?keyword=',
        'yg':'https://www.youtube.com/results?search_query=',
        'dy':'https://www.douyin.com/root/search/',
        'ks':'https://www.kuaishou.com/search/video?searchKey=',
        'xhs':'https://www.xiaohongshu.com/search_result?keyword=',
        //学术类
        'zw':'https://kns.cnki.net/kns8s/defaultresult/index?kw=',
        'gp': 'https://scholar.google.com/scholar?q=',
        'bp':'https://xueshu.baidu.com/s?wd=',
        'sd': 'https://www.sciencedirect.com/search?qs=',
        'rg': 'https://www.researchgate.net/search?q=',
        'sp': 'https://link.springer.com/search?new-search=true&query=',
        //翻译类
        'gt': 'https://translate.google.com/?hl=zh-CN&sl=auto&tl=en&text=',
        'dt': 'https://www.deepl.com/translator#zh/en/',
        'bt':'https://fanyi.baidu.com/mtpe-individual/multimodal?query=',
        //工具类
        'wd': 'https://www.bing.com/dict/search?q=',
        'wjbk':'https://zh.wikipedia.org/wiki/',
        'bdbk':'https://baike.baidu.com/item/',
        //购物网站
       'tb': 'https://s.taobao.com/search?q=',
       'jd':'https://search.jd.com/Search?keyword=',
       'xy':'https://www.goofish.com/search?q=',
       'scihub':'https://sci-hub.st/',
    
    },
    VIDEO_PROCESSORS: {
        bilibili: 'https://snapany.com/zh/bilibili',
        youtube: 'https://zh.loader.to/1/1080p-video-downloader.html',
        xhsd:'https://www.xiazaitool.com/xhs',
        txsp:'https://www.kedou.life/',
     
  
    },
    SHORTCUTS: {
        '-bd': 'https://www.baidu.com/',
        '-gg': 'https://www.google.com/',
        '-gzh':'https://mp.weixin.qq.com/cgi-bin/home?t=home/index&lang=zh_CN&token=562391244',
        '-txsp':'https://v.qq.com/',
        '-xy':'https://www.goofish.com/',
        '-scihub': 'https://sci-hub.st/',


        '-ks':'https://www.kuaishou.com/',
        '-by': 'https://www.bing.com/',
        '-sg': 'https://www.so.com/',
        '-gp': 'https://scholar.google.com/scholar?',
        
        '-gpu1':'https://colab.research.google.com/drive/1-sXNxQAVA2tbCEwfqIqwWRPaMy8742s3?authuser=1',
        '-gpu2':'https://colab.research.google.com/drive/1YEubTec38W9ZMkFghCpmrdhO0r818PzY',
        '-gpu3':'https://colab.research.google.com/drive/1UZGvwCA5GDg1Ppew-DMeGaEpRCKMVge2',
        '-gpu4':'https://colab.research.google.com/drive/1cLYeA7bXitNRG9l1CH0pbyWP34u61bAa',

        '-xhs':'https://www.xiaohongshu.com/explore',
        '-gzhpb':'https://markdown.com.cn/editor',

        '-lp':'./ohtml/literature.html',
        '-gas':'./ohtml/GA-search.html',
        '-diary': './diary.html',
        '-browser': './ohtml/browser.html',
        '-uk': './asset/%E8%8B%B1%E5%9B%BD%E3%80%81%E8%8B%B1%E6%A0%BC%E5%85%B0%E3%80%81%E5%A4%A7%E4%B8%8D%E5%88%97%E9%A2%A0%E3%80%81%E4%B8%8D%E5%88%97%E9%A2%A0%E7%BE%A4%E5%B2%9B%E6%8C%87%E7%9A%84%E6%98%AF%E5%93%AA%E4%BA%9B%E5%8C%BA%E5%9F%9F.mp4',
        '-bzfzlyl': './asset/b%E7%AB%99%E9%9D%9E%E4%B8%BB%E6%B5%81%E8%AF%AD%E5%BD%95.mp4',
        '-1998nwynkymzytyyh': './asset/1998%E5%B9%B4%E7%BB%B4%E4%B9%9F%E7%BA%B3%E4%B8%AD%E5%A4%A7%E4%B9%90%E5%9B%A2%E9%9F%B3%E4%B9%90%E4%BC%9A.mp4',
        '-ygmljts': './asset/%E6%B2%B9%E7%AE%A1%E9%A9%AC%E8%84%B8%E5%A7%90%E8%B0%88%E6%B0%B4.mp4',
        '-bztddtdxsfx': './asset/b%E7%AB%99%E6%AA%80%E4%B8%9C%E4%B8%9C%E8%B0%88%E5%A4%A7%E5%AD%A6%E7%94%9F%E6%96%B9%E5%90%91.mp4',
        '-sjmnmjd': './asset/%E7%9B%9B%E5%A9%95%E6%B2%A1%E9%82%A3%E4%B9%88%E7%AE%80%E5%8D%95.mp3',

        '-rus': 'D:/1-文档/7-html/2-html-case/short-video/1-ens-rus.html',
        '-chi': 'D:/1-文档/7-html/2-html-case/short-video/2-ens-chi.html',
        '-jjx': 'D:/1-文档/7-html/2-html-case/short-video/3-静静香.html',
        '-sjww': 'D:/1-文档/7-html/2-html-case/short-video/4-水晶娃娃.html',
        '-ttx': 'D:/1-文档/7-html/2-html-case/short-video/5-甜甜萱.html',
        '-xin': 'D:/1-文档/7-html/2-html-case/short-video/6-欣.html',

        '-ddlj': 'D:/1-文档/7-html/2-html-case/normal-video/淡淡逻辑.html',
        '-nj': 'D:/1-文档/7-html/2-html-case/normal-video/内经系列.html',
        '-zj': 'D:/1-文档/7-html/2-html-case/normal-video/针灸系列.html',

        '-scihub':'https://www.sci-hub.se/',

        '-pdftoword':'https://smallpdf.com/',
        '-mp3save1': 'https://www.myfreemp3.com.cn/',
        '-mp3save2': 'https://www.44h4.com/',

        '-zw': 'https://www.cnki.net/',
        '-claude': 'https://claude.ai/new',
        '-gpt': 'https://chatgpt.com/',
        '-wjbk': 'https://zh.wikipedia.org/wiki/Wikipedia:%E9%A6%96%E9%A1%B5',
        '-wrzd': 'https://cn.bing.com/dict/search?q=actual%20scenario&FORM=BDVSP6&cc=cn',
        '-if': 'https://www.letpub.com.cn/',
        '-dkwd': 'https://www.doc88.com/',
        '-gh': 'https://github.com/',
        '-zttb': 'https://www.iconfont.cn/',
        '-icon': 'https://icon-icons.com/',
        '-jxws': 'https://v.jxntv.cn/',
        '-xhw': 'https://www.xinhuanet.com/',
        '-cctv': 'https://www.cctv.com/',
        '-fhw': 'https://www.ifeng.com/',
        '-cxw': 'https://www.caixin.com/',
        '-bbc': 'https://www.bbc.com/',
        '-cnn': 'https://www.cnn.com/',
        '-nysb': 'https://www.nytimes.com/',
        '-britishspruce': 'https://blogs.napier.ac.uk/cwst/what-is-british-spruce/',
        '-copilot': 'https://www.bing.com/chat?q=Microsoft+Copilot&FORM=hpcodx',
        '-sms':'https://sms-activate.io/cn',

        '-gpt': 'https://chatgpt.com/',
        '-gemini': 'https://ai.google/',
        '-ib': 'https://www.ibm.com/watson',
        '-ms': 'https://www.microsoft.com/ai',
        '-nv': 'https://www.nvidia.com/en-us/ai/',
        '-dm': 'https://deepmind.com/',
        '-hf': 'https://huggingface.co/',
        
        '-bv': 'https://www.bilibili.com/',
        '-yg': 'https://www.youtube.com/',
        '-vm': 'https://vimeo.com/',
        '-dm': 'https://www.dailymotion.com/',
        '-tw': 'https://www.twitch.tv/',
        '-fb': 'https://www.facebook.com/watch/',
        '-pc': 'https://www.peach.com/',

        // 期刊
        '-woodscitech': 'https://www.springer.com/journal/00226',
        '-jws': 'https://link.springer.com/journal/10086',
        '-fpj': 'https://www.forestprodjournal.org/',
        '-wfs': 'https://wfs.swst.org/',
        '-cjfr': 'https://www.nrcresearchpress.com/journal/cjfr',
        '-jse': 'https://ascelibrary.org/journal/jsendh',
        '-jbp': 'https://www.techno-press.org/content/?page=journal&journal=jbpe',
        '-cbm': 'https://www.journals.elsevier.com/construction-and-building-materials',
        '-jcem': 'https://www.tandfonline.com/journal/tcem20',
        '-sei': 'https://www.isei.society',
        '-jsdb': 'https://onlinelibrary.wiley.com/journal/15412204',
        '-awst': 'https://journals.sagepub.com/home/awst',
        '-ijbpa': 'https://www.emerald.com/insight/publication/issn/1755-0478',
        '-jae': 'https://ascelibrary.org/journal/jaeied',
        '-jpcf': 'https://ascelibrary.org/journal/jpcfd4',
        '-mat': 'https://www.mdpi.com/journal/materials',
        '-wfsci': 'https://wfs.swst.org/index.php/wfs',
        '-jcsr': 'https://www.journals.elsevier.com/journal-of-constructional-steel-research',
        '-es': 'https://www.journals.elsevier.com/engineering-structures',
        '-schm': 'https://onlinelibrary.wiley.com/journal/15452268'
    }
};
